trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/*
      - package.json
      - vite.config.js
      - tailwind.config.js

pr:
  branches:
    include:
      - main
  paths:
    include:
      - src/*
      - package.json
      - vite.config.js
      - tailwind.config.js

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: npm_config_cache
    value: $(Pipeline.Workspace)/.npm

stages:
  - stage: Build
    displayName: Build React App
    jobs:
      - job: BuildJob
        displayName: Build and Create Artifact
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - task: Cache@2
            inputs:
              key: 'npm | "$(Agent.OS)" | package-lock.json'
              restoreKeys: |
                npm | "$(Agent.OS)"
              path: $(npm_config_cache)
            displayName: 'Cache npm dependencies'

          - script: |
              npm ci
              npm run build
            displayName: 'Install dependencies and build app'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'dist'
              ArtifactName: 'drop'
              publishLocation: 'Container'
            displayName: 'Publish Artifact to Drop'
